### ISSUE TITLE
What hardware do I need?

### ISSUE THREAD

**Issue by pinpox** [EneOli/unifi-voucher-terminal#1]
Hey, cool project! I have an EPSON TM88-II that I would like to use with a raspi, do you have any information on how to connect it? I'm not sure what adapter I need for this, serial port is new to me.

**Comment by eneoli** [comment]
Hi, you need a RS232 TTL converter. I'm using this one:

https://www.pollin.de/p/rs232-ttl-wandler-mit-max3232-810358

an it is directly wired up to the UART Ports of the raspberry pi.

Python has a library for connecting to serial ports.

**Comment by pinpox** [comment]
Thanks for the info, ordering one right now! I'm looking at how the serial communication is done here:
https://github.com/EneOli/unifi-voucher-terminal/blob/main/terminal/printer.py How did you find out the hex values? Can I print arbitrary images with that aswell? Not sure where to find a reference of commands
